// This project's article: an ordered list of blocks rendered top to bottom on its detail page.
//   { type: 'paragraph', text: 'Some prose.' }
//   { type: 'image', src: 'assets/images/sjhw/2.jpg', caption: 'Optional caption.' }  // src: a single file, or a directory of images
//   { type: 'video', src: 'https://youtu.be/VIDEO_ID', title: 'Optional header.', caption: 'Optional caption.' }  // src: a YouTube link, or a file in assets/videos
//   { type: 'heading', text: 'A subheading.' }
//   { type: 'list', items: ['First item.', { text: 'Item with sub-points.', items: ['Nested one.', 'Nested two.'] }] }
//   { type: 'download', src: 'CV.pdf', label: 'Optional button label.' }  // src: a file in /public
export const content = [
    { type: 'heading', text: "Writer's Room" },
    { type: 'paragraph', text: "Since I joined my school I have been participating weekly in the Writer’s Room club, which I have loved – a chance to refine and maintain creative writing skills, which were all too rarely taught in our classrooms in my view. Having entered the Walter Scott Young Writer’s Award for 2025 with the piece Florentine Skies, a few months later I found myself shortlisted for my age group in a list of around 10 from a national competition. As a result, it was also published in our school’s annual Lion Print magazine, and there is to this day a poster in the English corridor bearing my achievement. You can read it below if you wish." },
    { type: 'heading', text: "Florentine Skies" },
    { type: 'paragraph', text: "I wonder what the sky tastes like. The morning sky is a soupy concoction of froth and fluff and cauliflower patches, glistening with the eggy blood spilled from the sun, swimming in a turquoise bowl. Birds, like pepper, dot the sky as they flutter along their perpetual pilgrimage, their destination lost in their journey. An airy mist dances in the valleys, choreographed by the planet’s gentle breath, before the day heats up and burns it all away." },
    { type: 'paragraph', text: "Florence, from up here, is a beautifully uneven array of crimson tiles, shattered into hundreds of homes, dwellings, and churches. Cobblestone alleyways wind their way among the rooftops, like stone-cold blood vessels in some dormant creature. In my mind, those vessels really do carry Florence’s blood, as age-old traditions and trade flow through its veins, radiating life and culture." },
    { type: 'paragraph', text: "The mountainous outskirts of the city are where the other half of Tuscan culture lies. Rolling, green hills, made of olives trees and built on tradition, make up the landscape. The odd hut pierces the verdant view, usually a farmer’s residence, and sometimes an olive press. Back here, in the fields surrounding the tower, we have our own olive grove. Every year, in the picking season, we go and hand-pick each olive and let them drop onto nets we’ve used for generations. After tipping the contents of the nets into massive wooden crates, we take them by cart to our local press. This is my favourite part - the cogs and wheels and machinery, all operated by hand. Each of the parts working for one purpose and one purpose only, and if one of them failed, nothing would work. It is an ingeniously complex marvel of engineering." },
    { type: 'paragraph', text: "It is that machine, and the wonders of nature in innovation, that planted a seed in my mind - a seed that I’m sure will stick with me for life. That seed is already growing in my brain, sprouting its vivid roots of creativity - and its fruits have become physical. Down in the Cantina, deep below the tower’s courtyard, I have been working on my most complex, adventurous, and wonderfully absurd project yet - a flying machine. It is made to represent nature’s ingenuity, to replicate a bird - specifically an Upupa, a uniquely crested bird that resides in one of the tower’s arrow-slits. These birds have been supernaturally encoded for flight, and my plan has been to replicate that design with my creation, using wood and silk. And finally, after a year of glue and wood and sweat and toil, the main frame is complete. All that remains now is to install the membrane and implement the mechanisms." },
    { type: 'paragraph', text: "I hop off my windowsill, my bare feet making contact with the rough wooden flooring and my mind frantically vibrating with joyous anticipation. Today would be the day I’d finish the entire project, and I could prove to the world that nature held all the answers. I bound down the flights of stairs, the odd slit in the thick stone walls letting the sun fall inside as a sharp beam of orange. I race excitedly out onto the courtyard, and then down the final steps to the Cantina door. As I open it, its wise, wooden smell evoked a host of memories. It is the door I have opened every day, rain or shine. It is the door I have opened to reveal the work I love, and it is the final barrier to unleash the innovative glow of the flying machine." },
    { type: 'paragraph', text: "I step inside, walk over to the silk, and begin lacing it between the slats of wood on the wings, stitching it up when the piece runs out. For the entire afternoon, all that fills my mind is silk and stitching, the scent of glue and silk hanging in the air." },
    { type: 'paragraph', text: "By the time I stitch the final round of silk, it is evening. Anticipation flutters about in my stomach, coaxing me to end this journey. It is really happening. It feel as if my machine has been building itself a personality, coming alive, and beckoning me to flight. It is calling me to swim in the sky among the Upupas, and I daren’t refuse." },
    { type: 'paragraph', text: "Now it is all ready. I fold up the wings, and open the double doors from the Cantina. It barely makes it through, and after pulling it up the stairs with its wheels, I drag it to the field, my heart threatening to thump out of my chest. I chose this field as it was clear, and gently sloping down towards the city beyond." },
    { type: 'paragraph', text: "I line up years of effort on to the field, and unfold the wings." },
    { type: 'paragraph', text: "The horizon is glowing, like a fire encapsulating the earth. The sun is sinking into it, and as it melts into the night, it suddenly becomes my life. This could all fail. Are these my last moments? My very existence is melting into the horizon, sinking into the night, where it could cease to exist. I could die tonight; my duty here is done." },
    { type: 'paragraph', text: "Tentatively, with my stomach wrung tight like a muslin cloth, I enter my machine. My hands and feet find their way to the controls. I flap, and flap, and use all that remains of my might to power the initial lift. I feel the whole structure gently rise off the ground, and with my mind frozen in wonder, I cannot tell if I am about to leave home forever or return to where I belonged." },
];
